//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaLiExpress.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DaLi_GameExpressEntities : DbContext
    {
        public DaLi_GameExpressEntities()
            : base("name=DaLi_GameExpressEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeveloperStudio> DeveloperStudio { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<Platform> Platform { get; set; }
        public virtual DbSet<Publisher> Publisher { get; set; }
    }
}
