//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace DaLiExpress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.DeveloperStudio = new HashSet<DeveloperStudio>();
            this.Platform = new HashSet<Platform>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "A name is required, please enter one...")]
        public string Name { get; set; }
        [Range(1, 100, ErrorMessage = "Please enter a Rating between 1 and 100")]
        public int Rating { get; set; }

        [Required(ErrorMessage = "A release date is required, please enter one...")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public System.DateTime Release { get; set; }
        public Nullable<int> PublisherID { get; set; }

        [DisplayName("Publishers")]
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DisplayName("Developer Studio")]
        public virtual ICollection<DeveloperStudio> DeveloperStudio { get; set; }

        [DisplayName("Platforms")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Platform> Platform { get; set; }
    }
}